# Generated by Django 2.0.4 on 2018-08-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MChamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcid', models.IntegerField(db_index=True, null=True)),
                ('sport', models.IntegerField(null=True)),
                ('countryid', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('prize', models.CharField(max_length=20, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('surface', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meid', models.IntegerField(db_index=True, null=True)),
                ('res', models.CharField(max_length=50, null=True)),
                ('dt', models.DateTimeField(db_index=True, null=True)),
                ('free', models.IntegerField(null=True)),
                ('champ', models.ForeignKey(null=True, on_delete=None, to='server.MChamp')),
            ],
        ),
        migrations.CreateModel(
            name='MPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpid', models.IntegerField(db_index=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('db', models.DateTimeField(null=True)),
                ('cid', models.IntegerField(null=True)),
                ('gender', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSetStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc', models.IntegerField(db_index=True)),
                ('meid', models.IntegerField(db_index=True)),
                ('pid', models.IntegerField(db_index=True)),
                ('tp', models.IntegerField(null=True)),
                ('tw', models.IntegerField(null=True)),
                ('s1w', models.IntegerField(null=True)),
                ('s1ws2l', models.IntegerField(null=True)),
                ('s1wml', models.IntegerField(null=True)),
                ('s1ws2lmw', models.IntegerField(null=True)),
                ('s1l', models.IntegerField(null=True)),
                ('s1ls2w', models.IntegerField(null=True)),
                ('s1lmw', models.IntegerField(null=True)),
                ('s1ls2wml', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mevent',
            name='p1',
            field=models.ForeignKey(null=True, on_delete=None, related_name='mplayer1', to='server.MPlayer'),
        ),
        migrations.AddField(
            model_name='mevent',
            name='p2',
            field=models.ForeignKey(null=True, on_delete=None, related_name='mplayer2', to='server.MPlayer'),
        ),
    ]
