# Generated by Django 2.0.4 on 2018-04-25 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField(unique=True)),
                ('venue', models.CharField(max_length=100)),
                ('open_date', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('timezone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('total_matched', models.FloatField(null=True)),
                ('start_time', models.DateTimeField()),
                ('betting_type', models.CharField(max_length=50)),
                ('market_time', models.DateTimeField()),
                ('market_type', models.CharField(max_length=50)),
                ('suspend_time', models.DateTimeField()),
                ('turn_in_play_enabled', models.BooleanField()),
                ('race_type', models.CharField(max_length=50, null=True)),
                ('has_processed', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sort_priority', models.IntegerField()),
                ('handicap', models.FloatField()),
                ('cloth_number', models.IntegerField(null=True)),
                ('stall_draw', models.IntegerField(null=True)),
                ('runner_id', models.BigIntegerField()),
                ('market', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trader.Market')),
            ],
        ),
        migrations.CreateModel(
            name='Tennis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.BigIntegerField(unique=True)),
                ('runner_id', models.BigIntegerField(unique=True)),
                ('player_name_1', models.CharField(max_length=100)),
                ('player_name_2', models.CharField(max_length=100)),
            ],
        ),
    ]
