# Generated by Django 2.0.4 on 2018-05-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tennis',
        ),
    ]
