# Generated by Django 2.0.4 on 2018-05-23 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trader', '0002_delete_tennis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_market_data_delayed', models.BooleanField()),
                ('status', models.CharField(max_length=50)),
                ('bet_delay', models.FloatField()),
                ('bsp_reconciled', models.BooleanField()),
                ('complete', models.BooleanField()),
                ('inplay', models.BooleanField()),
                ('number_of_winners', models.IntegerField()),
                ('number_of_runners', models.IntegerField()),
                ('number_of_active_runners', models.IntegerField()),
                ('last_match_time', models.DateTimeField(null=True)),
                ('total_matched', models.FloatField()),
                ('total_available', models.FloatField()),
                ('cross_matching', models.BooleanField()),
                ('runners_voidable', models.BooleanField()),
                ('version', models.BigIntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Market')),
            ],
        ),
        migrations.CreateModel(
            name='RunnerBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('adjustment_factor', models.FloatField(null=True)),
                ('last_price_traded', models.FloatField(null=True)),
                ('total_matched', models.FloatField(null=True)),
                ('back_price', models.FloatField(null=True)),
                ('back_size', models.FloatField(null=True)),
                ('lay_price', models.FloatField(null=True)),
                ('lay_size', models.FloatField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Book')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trader.Runner')),
            ],
        ),
    ]
